// Generated by CoffeeScript 1.10.0
var _, encryptor;

_ = require('underscore');

encryptor = require('./encryptor');

module.exports = (function() {
  _Class.prototype.algList = ['none', 'des-ede3', '', '', 'rsa'];

  _Class.prototype.hashList = ['none', 'md5', 'sha1'];

  _Class.getBusiness = function(pkg, options) {
    var base, business;
    pkg = JSON.parse(pkg);
    business = pkg.dataPackage.business;
    (base = pkg.dataPackage).encryptFlag || (base.encryptFlag = pkg.dataPackage.cryptFlag);
    if (pkg.dataPackage.encryptFlag === 0) {
      return business;
    } else {
      business = encryptor.decrypt(this.prototype.algList[pkg.dataPackage.encryptFlag], business, options.key);
      return business;
    }
  };

  function _Class(business, options) {
    options = _.defaults({}, options, {
      pkgFlag: 1,
      errCode: 0,
      errMsg: '',
      encryptFlag: 1,
      hashFlag: 1,
      signatureFlag: 0
    });
    this.pkgFlag = options.pkgFlag;
    this.errCode = options.errCode;
    this.errMsg = options.errMsg;
    this.crc = 0;
    business = encryptor.encrypt(this.algList[options.encryptFlag], JSON.stringify(business), options.key);
    this.dataPackage = {
      encryptFlag: options.encryptFlag,
      cryptFlag: options.encryptFlag,
      hashFlag: options.hashFlag,
      signatureFlag: options.signatureFlag,
      business: business,
      hash: encryptor.hash(this.hashList[options.hashFlag], business)
    };
  }

  return _Class;

})();
