// Generated by CoffeeScript 1.10.0
var _destroy, args, bodyParser, cookieParser, express, http, parser, rest, server, session, store;

parser = require('./common/parser');

http = require('http');

bodyParser = require('body-parser');

session = require('express-session');

cookieParser = require('cookie-parser');

express = require('express');

args = parser.parseArgs();

rest = express();

server = http.createServer(rest);

rest.use(bodyParser.text());

store = new session.MemoryStore();

_destroy = store.destroy;

store.destroy = function(sessionId, callback) {
  _destroy.call(store, sessionId, callback);
  delete emulators[sessionId];
  console.log('session destroy ok.');
};

rest.use(cookieParser());

rest.use(session({
  key: 'JSESSIONID',
  store: store,
  resave: false,
  saveUninitialized: false,
  secret: 'keyboard cat'
}));

rest.use("/" + args.app_name, require('./router/framework'), require('./router/static'), require('./router/mockapi'));

server.listen(args.port, args.addr, function() {
  console.log("模拟服务器已启动[http://" + args.addr + ":" + args.port + "/" + args.app_name + "]");
});
