// Generated by CoffeeScript 1.10.0
var ArgumentParser, args, i, j, parser, pkgObj, ref;

pkgObj = require('../../package.json');

ArgumentParser = require('argparse').ArgumentParser;

parser = new ArgumentParser({
  version: pkgObj.version,
  addHelp: true,
  description: 'Pastry测试服务器',
  prog: 'emulator-server'
});

args = [
  ['-a', '--addr'], {
    help: '指定监听IP',
    defaultValue: '0.0.0.0'
  }, ['-p', '--port'], {
    help: '指定监听端口。',
    defaultValue: 3002
  }, ['-n', '--app-name'], {
    help: '指定应用服务名称。',
    defaultValue: 'TestServer'
  }, ['-w', '--workdir'], {
    help: '指定工作目录。',
    defaultValue: '.'
  }, ['--verbose'], {
    help: '设置是否打印详细日志。',
    defaultValue: false
  }
];

for (i = j = 0, ref = args.length / 2; 0 <= ref ? j < ref : j > ref; i = 0 <= ref ? ++j : --j) {
  parser.addArgument(args[i * 2], args[i * 2 + 1]);
}

module.exports = parser;
