// Generated by CoffeeScript 1.10.0
var _, common_data, common_data_name, fs, mkPath, path, rootPath, slice;

slice = [].slice;

_ = require('underscore');

fs = require('fs');

path = require('path');

rootPath = path.resolve(__dirname + "/../../");

common_data_name = 'common_data';

common_data = __dirname;

while (common_data !== '/' && fs.readdirSync(common_data).indexOf(common_data_name) === -1) {
  common_data = path.resolve(common_data + '/..');
}

common_data = path.join(common_data, common_data_name);

mkPath = function() {
  var base;
  base = 1 <= arguments.length ? slice.call(arguments, 0) : [];
  return function() {
    var args;
    args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    return path.join.apply(path, base.concat.apply(base, args));
  };
};

module.exports = {
  normalize: function(str) {
    return path.normalize(str.replace(/\\|\//g, path.sep));
  },
  root: mkPath(rootPath),
  data: mkPath(rootPath, 'data'),
  common_data: mkPath(common_data),
  wwwroot: mkPath(rootPath, 'wwwroot'),
  lib: {
    pastry: mkPath(rootPath, 'data', 'lib', 'pastry')
  },
  template: {
    pastry: mkPath(rootPath, 'data', 'template', 'pastry'),
    config: mkPath(rootPath, 'data', 'template', 'config')
  }
};
