// Generated by CoffeeScript 1.10.0
var express, favicon, paths, router;

express = require('express');

favicon = require('serve-favicon');

paths = require('../common/paths');

router = express.Router();

router.use(favicon(paths.wwwroot('images', 'favicon.ico')));

router.use(express["static"](paths.wwwroot()));

module.exports = router;
